name: Build and Push (Triton-slim)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to NVIDIA NGC (nvcr.io)
        uses: docker/login-action@v3
        with:
          registry: nvcr.io
          username: ${{ secrets.NGC_USERNAME }}   # $oauthtoken
          password: ${{ secrets.NGC_API_KEY }}    # your API key

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/runpod-triton-slim:latest
          build-args: |
            TRITON_VERSION=24.09
