name: Build and Push Docker Image

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # NGC login
      - name: Login to NVIDIA NGC (nvcr.io)
        uses: docker/login-action@v3
        with:
          registry: nvcr.io
          username: ${{ secrets.NGC_USERNAME }}   # -> $oauthtoken
          password: ${{ secrets.NGC_API_KEY }}    # -> your API key

      # Docker Hub login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # (optional) quick sanity check that NGC auth works
      - name: Pull Triton base to verify NGC auth
        run: docker pull nvcr.io/nvidia/tritonserver:24.09-py3

      # Build & push
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/runpod-triton-pytorch:latest
          build-args: |
            TRITON_VERSION=24.09
